import json
import os

import requests

from autonomous import log

# --- Configuration Example ---
#  set these environment variables in your .env file or Docker Compose
# TODO:  fix this later
FOUNDRY_VTT_URL = "https://foundryvtt-rest-api-relay.fly.dev"
FOUNDRY_API_TOKEN = "e774d9f03f8f7d668fe04d79fe66eda7"
# Initialize the client globally or within your app context
# foundry_client = FoundryClient()


class FoundryClient:
    """
    A client wrapper for interacting with the foundryvtt-rest-api-relay.
    """

    def __init__(
        self, world_name, base_url=FOUNDRY_VTT_URL, api_token=FOUNDRY_API_TOKEN
    ):
        """
        Initializes the client with the Foundry VTT base URL and the API token.
        Args:
            base_url (str): The URL where Foundry VTT is accessible (e.g., 'https://myfoundry.com').
            api_token (str): The API Token generated by the foundryvtt-rest-api-relay module.
        """
        # Ensure the URL is correctly formatted for the relay's base path
        self.base_url = f"{base_url.rstrip('/')}"
        self.client_id = None  # Will be set after connecting to a world
        self.headers = {
            # The API Relay requires the token to be sent in the header
            "x-api-key": api_token,
            "Content-Type": "application/json",
        }
        for client in self.get_worlds():
            print(client)
            if client["customName"].lower() == world_name.lower():
                self.client_id = client["id"]
                break
        if not self.client_id:
            raise ValueError(f"World '{world_name}' not found in Foundry VTT.")

        self.headers |= {
            "x-client-id": self.client_id,
        }

    def _request(self, method, endpoint, **kwargs):
        """Internal method to handle requests and error processing."""
        if self.client_id:
            url = f"{self.base_url}/{endpoint}?clientId={self.client_id}"
        else:
            url = f"{self.base_url}/{endpoint}"
        log(url, self.headers)

        try:
            response = requests.request(method, url, headers=self.headers, **kwargs)
            log(response.status_code, response.text)
            response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)

            # Foundry API may return text or empty content, handle JSON decoding gracefully
            if response.text:
                return response.json()
            return {}

        except requests.exceptions.HTTPError as e:
            print(
                f"HTTP Error {e.response.status_code} on {method} {url}: {e.response.text}"
            )
            return {
                "error": f"HTTP Error: {e.response.status_code}",
                "detail": e.response.text,
            }
        except requests.exceptions.RequestException as e:
            print(f"Network or Connection Error: {e}")
            return {"error": "Connection Error", "detail": str(e)}

    # --- API Methods ---

    def get_worlds(self):
        """Retrieves a list of available worlds."""
        # Endpoint example: GET /api/relay/worlds
        response = self._request("GET", "clients")
        return response.get("clients", [])

    def get_world_scenes(self):
        """Retrieves all scenes within a specific world."""
        # Endpoint example: GET /api/relay/worlds/world_id/scenes
        return self._request("GET", f"search&documentType=Scene")

    def get_world_actors(self):
        """Retrieves all actors within a specific world."""
        # Endpoint example: GET /api/relay/worlds/world_id/actors
        return self._request("GET", f"search&documentType=Actor")

    def get_world_items(self):
        """Retrieves all items within a specific world."""
        # Endpoint example: GET /api/relay/worlds/world_id/items
        return self._request("GET", f"search&documentType=Item")

    def update_actor(self, actor_id, update_data):
        """Updates a Foundry actor (character)."""
        # Endpoint example: PATCH /api/relay/worlds/world_id/actors/actor_id
        return self._request(
            "PATCH",
            f"worlds/{self.client_id}/actors/{actor_id}",
            data=json.dumps(update_data),
        )

    def update_item(self, world_id, item_id, update_data):
        """Updates a Foundry item."""
        # Endpoint example: PATCH /api/relay/worlds/world_id/items/item_id
        return self._request(
            "PATCH",
            f"worlds/{world_id}/items/{item_id}",
            data=json.dumps(update_data),
        )

    def create_actor(self, world_id, actor_data):
        """Creates a new Foundry actor (character)."""
        # Endpoint example: POST /api/relay/worlds/world_id/actors
        return self._request(
            "POST",
            f"worlds/{world_id}/actors",
            data=json.dumps(actor_data),
        )

    def create_item(self, world_id, item_data):
        """Creates a new Foundry item."""
        # Endpoint example: POST /api/relay/worlds/world_id/items
        return self._request(
            "POST",
            f"worlds/{world_id}/items",
            data=json.dumps(item_data),
        )

    def create_scene(self, world_id, scene_data):
        """Creates a new Foundry scene."""
        # Endpoint example: POST /api/relay/worlds/world_id/scenes
        return self._request(
            "POST",
            f"worlds/{world_id}/scenes",
            data=json.dumps(scene_data),
        )
