from models.systems.basesystem import BaseSystem


class SciFiSystem(BaseSystem):
    meta = {
        "allow_inheritance": True,
        "strict": False,
    }
    _genre = "Sci-Fi"

    _currency = {
        "credits": "cc",
    }

    _music_lists = BaseSystem._music_lists | {
        "social": ["scifithemesong.mp3"],
        "encounter": ["scifipursuit.mp3"],
        "combat": [
            "scifibattle.mp3",
        ],
        "exploration": ["scificreepy.mp3", "scifisuspense.mp3"],
        "stealth": [
            "scifisuspense.mp3",
        ],
    }

    _titles = {
        "city": "Planet",
        "creature": "Alien",
        "faction": "Faction",
        "region": "Star-System",
        "world": "Galactic-Sector",
        "location": "Location",
        "shop": "Shop",
        "vehicle": "Vehicle",
        "district": "Outpost",
        "item": "Tech",
        "encounter": "Encounter",
        "character": "Character",
    }

    _traits_list = {
        "city": [
            "Abandoned Colony",
            "Alien Ruins",
            "Anarchists",
            "Battleground",
            "Civil War",
            "Colonized Population",
            "Doomed",
            "Eugenic Cult",
            "Fallen Hegemon",
            "Feral World",
            "Forbidden Technology",
            "Freak Weather",
            "Genetic Engineering",
            "Hivemind",
            "Hostile Space",
            "Imperialism",
            "Inquisition",
            "Isolationism",
            "Lost Colony",
            "Military Dictatorship",
            "Megacorps",
            "Minimal Contact",
            "Outpost World",
            "Police State",
            "Post-Apocalyptic",
            "Pre-Industrial",
            "Pre-Contact",
            "Pre-Spaceflight",
            "Rebellion",
            "Religious Fanaticism",
            "Resource Scarcity",
            "Rogue AI",
            "Rogue Planet",
            "Rogue Starship",
            "Rogue World",
            "Theocracy",
            "Totalitarianism",
            "Tomb World",
            "Utopia",
            "War World",
            "Warriors",
            "Warlords",
            "Zombies",
        ],
        "creature": [
            "aggressive",
            "cunning",
            "deceptive",
            "intelligent",
            "loyal",
            "savage",
            "sneaky",
            "vicious",
        ],
        "faction": [
            "colonists",
            "deep rooted",
            "cult",
            "suspicious",
            "violent",
            "sinister",
            "fanatical",
            "racist",
            "egalitarian",
            "ambitious",
            "corrupt",
            "charitable",
            "greedy",
            "generous",
            "imperialist",
            "isolationist",
            "mercenary",
        ],
        "region": [
            "dangerous",
            "uninhabited",
            "inhospitable",
            "beautiful",
            "lush",
            "politically unstable",
            "desolate",
            "peaceful",
            "chaotic",
            "warring",
            "hostile",
            "welcoming",
        ],
        "world": [
            "bohemian",
            "rude",
            "aggressive",
            "proud",
            "distrustful",
            "anarchic",
            "aristocratic",
            "bureaucratic",
            "theocratic",
            "tribalist",
        ],
        "location": [
            "bohemian",
            "rude",
            "aggressive",
            "proud",
            "distrustful",
            "anarchic",
            "aristocratic",
            "bureaucratic",
            "theocratic",
            "tribalist",
        ],
        "shop": [
            "bohemian",
            "rude",
            "aggressive",
            "proud",
            "distrustful",
            "anarchic",
            "aristocratic",
            "bureaucratic",
            "theocratic",
            "tribalist",
        ],
        "vehicle": [
            "fast",
            "slow",
            "stealthy",
            "heavily armed",
            "heavily armored",
            "lightly armed",
            "lightly armored",
            "well designed",
            "poorly designed",
            "well maintained",
            "poorly maintained",
        ],
        "district": [
            "bohemian",
            "rude",
            "aggressive",
            "proud",
            "distrustful",
            "anarchic",
            "aristocratic",
            "bureaucratic",
            "theocratic",
            "tribalist",
        ],
        "item": [
            "common",
            "uncommon",
            "rare",
            "very rare",
            "legendary",
            "artifacts",
            "cursed",
            "sentient",
            "magical",
            "mundane",
            "unique",
        ],
        "encounter": [
            "ambush",
            "puzzle",
            "trap",
            "combat",
            "social",
            "stealth",
        ],
        "character": [
            "secretly evil",
            "shy and gentle",
            "outgoing and imaginative",
            "unfriendly, but not unkind",
            "cruel and sadistic",
            "power-hungry and ambitious",
            "kind and helpful",
            "proud and self-absorbed",
            "silly, a prankster",
            "overly serious",
            "incredibly greedy",
            "extremely generous",
            "hardworking",
            "cowardly and insecure",
            "practical to a fault",
            "dangerously curious",
            "cautious and occasionally paranoid",
            "reckless, but heroic",
            "Ambition",
            "Avarice",
            "Bitterness",
            "Courage",
            "Cowardice",
            "Curiosity",
            "Deceitfulness",
            "Determination",
            "Devotion to a cause",
            "Filiality",
            "Hatred",
            "Honesty",
            "Hopefulness",
            "Love of a person",
            "Nihilism",
            "Paternalism",
            "Pessimism",
            "Protectiveness",
            "Resentment",
            "Shame",
        ],
    }
